name: Quality Checks

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  quality:
    name: Quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5
      - name: Setup
        run: npm run setup
      - name: Linting
        run: npm run lint
      - name: Prettier check
        run: npm run prettier
      - name: Test
        run: npm run test

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5
      - name: Init
        run: npm run setup
      - name: Build
        run: npm run type-check
